CREATE TABLE [dbo].[Newtable]
(
[id] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Newtable] ADD CONSTRAINT [PK__Newtable__3213E83F64428AC1] PRIMARY KEY CLUSTERED ([id]) ON [PRIMARY]
GO
